# Generated by Django 4.2.29 on 2026-04-17 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listen_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='music.track'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trackdailystat',
            unique_together={('track', 'date')},
        ),
        migrations.AddIndex(
            model_name='streamhistory',
            index=models.Index(fields=['created_at'], name='analytics_s_created_e92cca_idx'),
        ),
        migrations.AddIndex(
            model_name='streamhistory',
            index=models.Index(fields=['track', 'created_at'], name='analytics_s_track_i_77034f_idx'),
        ),
    ]
