# Generated by Django 4.2.29 on 2026-04-21 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downloadhistory',
            unique_together={('user', 'track')},
        ),
    ]
