# Generated by Django 4.2.3 on 2026-05-18 05:17

import apps.core.services
import apps.core.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True)),
                ('block_note', models.TextField(blank=True, null=True)),
                ('reject_reason', models.IntegerField(blank=True, null=True)),
                ('reject_note', models.TextField(blank=True, null=True)),
                ('short_id', models.CharField(db_index=True, default=apps.core.utils.generate_short_id, max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('image', models.ImageField(max_length=500, upload_to=apps.core.services.get_path_upload_image_album, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], default='single', max_length=10)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='releases.release')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
