# Generated by Django 4.2.29 on 2026-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='is_private',
        ),
    ]
