# Generated by Django 4.2.29 on 2026-04-23 07:27

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_remove_release_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(max_length=500, upload_to=apps.core.services.get_path_upload_image_album, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
