# Generated by Django 4.2.29 on 2026-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_alter_release_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='block_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='block_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True),
        ),
    ]
