# Generated by Django 4.2.29 on 2026-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_release_block_note_alter_release_block_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='reject_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='reject_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
