version: "3.8"

services:
  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    networks:
      - app_net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app_net
volumes:
  pgdata:
networks:
  app_net:
    driver: bridge
