# Generated by Django 4.2.29 on 2026-04-27 17:04

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/profile.jpeg', max_length=500, null=True, upload_to=apps.core.services.get_path_upload_image_user, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
