# Generated by Django 4.2.29 on 2026-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_block_note_alter_user_block_reason_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
