# Generated by Django 4.2.29 on 2026-05-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Super Admin'), ('content_mod', 'Content Moderator'), ('account_mod', 'Account Moderator')], null=True),
        ),
    ]
