# Generated by Django 4.2.3 on 2025-05-02 13:56

import apps.core.services
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('image', models.ImageField(blank=True, default='default/track.jpg', null=True, upload_to=apps.core.services.get_path_upload_image_album, validators=[apps.core.services.validate_image_size])),
                ('file_url', models.FileField(blank=True, default='default/audio.jpg', null=True, upload_to=apps.core.services.get_path_upload_audio_track, validators=[apps.core.services.validate_audio_size])),
                ('duration', models.DurationField(blank=True)),
                ('release_date', models.DateField(null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('listens', models.BigIntegerField(default=0)),
                ('downloads', models.BigIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='genres.genre')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['-created_at'],
            },
        ),
    ]
