<<<<<<< HEAD
# Generated by Django 4.2.29 on 2026-05-16 10:13
=======
# Generated by Django 4.2.29 on 2026-04-17 10:22
>>>>>>> d0d092557be3048ad089e799de52192222719817

import apps.core.services
import apps.core.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
=======
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
>>>>>>> d0d092557be3048ad089e799de52192222719817
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
<<<<<<< HEAD
                ('block_reason', models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True)),
                ('block_note', models.TextField(blank=True, null=True)),
                ('short_id', models.CharField(db_index=True, default=apps.core.utils.generate_short_id, max_length=15, unique=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
=======
                ('short_id', models.CharField(db_index=True, default=apps.core.utils.generate_short_id, max_length=15, unique=True)),
>>>>>>> d0d092557be3048ad089e799de52192222719817
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_url', models.FileField(help_text='Streaming', max_length=500, upload_to=apps.core.services.get_path_upload_audio_track, validators=[apps.core.services.validate_audio_size, apps.core.services.validate_audio_extension])),
                ('preview_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.services.get_path_upload_preview_track)),
                ('lyrics_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.services.get_path_upload_lyrics_track)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Dung lượng file (Bytes)', null=True)),
                ('is_premium_only', models.BooleanField(default=False, help_text='Premium track for premium users only')),
                ('listens', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('block_reason', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True)),
>>>>>>> d0d092557be3048ad089e799de52192222719817
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='artists.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='genres.genre')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('file_url', models.FileField(help_text='URL of the canvas video', upload_to='')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='track__title', unique=True)),
                ('thumbnail', models.ImageField(blank=True, default='default/canvas_thumbnail.jpg', null=True, upload_to='tracks/canvas/thumbnails/')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='music.track')),
            ],
            options={
                'verbose_name': 'Track Canvas',
                'verbose_name_plural': 'Track Canvases',
            },
        ),
    ]
