<<<<<<< HEAD
# Generated by Django 4.2.29 on 2026-05-16 10:13
=======
# Generated by Django 4.2.29 on 2026-04-17 10:22
>>>>>>> d0d092557be3048ad089e799de52192222719817

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('releases', '0001_initial'),
        ('music', '0001_initial'),
=======
        ('music', '0001_initial'),
        ('releases', '0001_initial'),
>>>>>>> d0d092557be3048ad089e799de52192222719817
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='release',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='releases.release'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_active', 'is_blocked'], name='music_track_is_acti_820c20_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['release', 'artist'], name='music_track_release_ca87c2_idx'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='releases.release'),
>>>>>>> d0d092557be3048ad089e799de52192222719817
        ),
    ]
