# Generated by Django 4.2.29 on 2026-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
