# Generated by Django 4.2.29 on 2026-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='block_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='block_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_active', 'is_blocked'], name='music_track_is_acti_820c20_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['release', 'artist'], name='music_track_release_ca87c2_idx'),
        ),
    ]
