# Generated by Django 4.2.29 on 2026-05-11 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_release_reject_note_release_reject_reason'),
        ('music', '0004_track_block_note_alter_track_block_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='releases.release'),
        ),
    ]
