# Generated by Django 4.2.29 on 2026-04-17 10:22

import apps.core.services
import apps.core.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('short_id', models.CharField(db_index=True, default=apps.core.utils.generate_short_id, max_length=15, unique=True)),
                ('stage_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='stage_name', unique=True)),
                ('image', models.ImageField(default='default/profile-picture.png', max_length=500, upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension])),
                ('is_verify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
            ],
            options={
                'verbose_name': 'Artist verification request',
                'verbose_name_plural': 'Artist verification requests',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Favorite artist',
                'verbose_name_plural': 'Favorite artists',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
