# Generated by Django 4.2.3 on 2026-05-18 05:17

import apps.core.services
import apps.core.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True)),
                ('block_note', models.TextField(blank=True, null=True)),
                ('short_id', models.CharField(db_index=True, default=apps.core.utils.generate_short_id, max_length=15, unique=True)),
                ('stage_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='stage_name', unique=True)),
                ('image', models.ImageField(max_length=500, upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension])),
                ('banner', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.services.get_path_upload_image_artist_banner, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension])),
                ('is_verify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.IntegerField(blank=True, null=True)),
                ('reject_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('identity_document', models.ImageField(null=True, upload_to='verifications/documents/')),
                ('social_link', models.URLField(max_length=500, null=True)),
                ('contact_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Artist verification request',
                'verbose_name_plural': 'Artist verification requests',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Favorite artist',
                'verbose_name_plural': 'Favorite artists',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
