# Generated by Django 4.2.3 on 2026-01-22 17:55

import apps.core.services
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='stage_name', unique=True)),
                ('image', models.ImageField(blank=True, default='default/profile.fpeg', upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size])),
                ('is_verify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
            ],
            options={
                'verbose_name': 'Artist verification request',
                'verbose_name_plural': 'Artist verification requests',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Favorite artist',
                'verbose_name_plural': 'Favorite artists',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
