# Generated by Django 4.2.29 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistverificationrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='contact_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='identity_document',
            field=models.ImageField(null=True, upload_to='verifications/documents/'),
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='social_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
