# Generated by Django 4.2.29 on 2026-05-07 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0003_remove_artistverificationrequest_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistverificationrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistverificationrequest',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='artists.artist'),
        ),
    ]
