# Generated by Django 4.2.29 on 2026-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artistverificationrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistverificationrequest',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Incomplete or unclear information'), (2, 'Low quality profile or document image'), (3, 'Social link is invalid or not owned'), (4, 'Stage name or content copyright issue'), (5, 'Other')], help_text='Lý do từ chối đơn (nếu có)', null=True),
        ),
    ]
