# Generated by Django 4.2.29 on 2026-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artistverificationrequest_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistverificationrequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='artist',
            name='block_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='reject_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistverificationrequest',
            name='reject_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Incomplete or unclear information'), (2, 'Low quality profile or document image'), (3, 'Social link is invalid or not owned'), (4, 'Stage name or content copyright issue'), (5, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='block_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Copyright Infringement'), (2, 'Sensitive Content'), (3, 'Artist Blocked'), (4, 'Other')], null=True),
        ),
    ]
