# Generated by Django 4.2.29 on 2026-05-09 17:24

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_remove_artistverificationrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(max_length=500, upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
