# Generated by Django 4.2.29 on 2026-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistverificationrequest',
            name='reject_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
