# Generated by Django 4.2.29 on 2026-05-11 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0008_alter_artistverificationrequest_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='favouriteartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
