# Generated by Django 4.2.29 on 2026-05-14 09:25

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_alter_favouriteartist_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.services.get_path_upload_image_artist_banner, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
