# Generated by Django 4.2.29 on 2026-04-23 07:27

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='default/genre.png', max_length=500, null=True, upload_to=apps.core.services.get_path_upload_image_genre, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
