# Generated by Django 4.2.29 on 2026-05-09 17:24

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='default/genre.jpg', max_length=500, null=True, upload_to=apps.core.services.get_path_upload_image_genre, validators=[apps.core.services.validate_image_size, apps.core.services.validate_image_extension]),
        ),
    ]
